//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// Interface representing the dbo.aspnet_Roles table.
    /// </summary>
    public interface IAspnetRoles
    {
        /// <summary>
        /// Gets or sets the ApplicationId column value.
        /// </summary>
        System.Guid ApplicationId { get; set; }
        /// <summary>
        /// Gets or sets the RoleId column value.
        /// </summary>
        System.Guid RoleId { get; set; }
        /// <summary>
        /// Gets or sets the RoleName column value.
        /// </summary>
        string RoleName { get; set; }
        /// <summary>
        /// Gets or sets the LoweredRoleName column value.
        /// </summary>
        string LoweredRoleName { get; set; }
        /// <summary>
        /// Gets or sets the Description column value.
        /// </summary>
        string Description { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.AspnetApplications"/> association.
        /// </summary>
        AIM.Data.AspnetApplications AspnetApplications { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.AspnetUsersInRoles"/> association.
        /// </summary>
        System.Data.Linq.EntitySet<AIM.Data.AspnetUsersInRoles> AspnetUsersInRolesList { get; set; }
    }
}
