//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// Interface representing the dbo.aspnet_Profile table.
    /// </summary>
    public interface IAspnetProfile
    {
        /// <summary>
        /// Gets or sets the UserId column value.
        /// </summary>
        System.Guid UserId { get; set; }
        /// <summary>
        /// Gets or sets the PropertyNames column value.
        /// </summary>
        string PropertyNames { get; set; }
        /// <summary>
        /// Gets or sets the PropertyValuesString column value.
        /// </summary>
        string PropertyValuesString { get; set; }
        /// <summary>
        /// Gets or sets the PropertyValuesBinary column value.
        /// </summary>
        System.Data.Linq.Binary PropertyValuesBinary { get; set; }
        /// <summary>
        /// Gets or sets the LastUpdatedDate column value.
        /// </summary>
        System.DateTime LastUpdatedDate { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.AspnetUsers"/> association.
        /// </summary>
        AIM.Data.AspnetUsers AspnetUsers { get; set; }
    }
}
