//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// Interface representing the dbo.aspnet_Membership table.
    /// </summary>
    public interface IAspnetMembership
    {
        /// <summary>
        /// Gets or sets the ApplicationId column value.
        /// </summary>
        System.Guid ApplicationId { get; set; }
        /// <summary>
        /// Gets or sets the UserId column value.
        /// </summary>
        System.Guid UserId { get; set; }
        /// <summary>
        /// Gets or sets the Password column value.
        /// </summary>
        string Password { get; set; }
        /// <summary>
        /// Gets or sets the PasswordFormat column value.
        /// </summary>
        int PasswordFormat { get; set; }
        /// <summary>
        /// Gets or sets the PasswordSalt column value.
        /// </summary>
        string PasswordSalt { get; set; }
        /// <summary>
        /// Gets or sets the MobilePIN column value.
        /// </summary>
        string MobilePIN { get; set; }
        /// <summary>
        /// Gets or sets the Email column value.
        /// </summary>
        string Email { get; set; }
        /// <summary>
        /// Gets or sets the LoweredEmail column value.
        /// </summary>
        string LoweredEmail { get; set; }
        /// <summary>
        /// Gets or sets the PasswordQuestion column value.
        /// </summary>
        string PasswordQuestion { get; set; }
        /// <summary>
        /// Gets or sets the PasswordAnswer column value.
        /// </summary>
        string PasswordAnswer { get; set; }
        /// <summary>
        /// Gets or sets the IsApproved column value.
        /// </summary>
        bool IsApproved { get; set; }
        /// <summary>
        /// Gets or sets the IsLockedOut column value.
        /// </summary>
        bool IsLockedOut { get; set; }
        /// <summary>
        /// Gets or sets the CreateDate column value.
        /// </summary>
        System.DateTime CreateDate { get; set; }
        /// <summary>
        /// Gets or sets the LastLoginDate column value.
        /// </summary>
        System.DateTime LastLoginDate { get; set; }
        /// <summary>
        /// Gets or sets the LastPasswordChangedDate column value.
        /// </summary>
        System.DateTime LastPasswordChangedDate { get; set; }
        /// <summary>
        /// Gets or sets the LastLockoutDate column value.
        /// </summary>
        System.DateTime LastLockoutDate { get; set; }
        /// <summary>
        /// Gets or sets the FailedPasswordAttemptCount column value.
        /// </summary>
        int FailedPasswordAttemptCount { get; set; }
        /// <summary>
        /// Gets or sets the FailedPasswordAttemptWindowStart column value.
        /// </summary>
        System.DateTime FailedPasswordAttemptWindowStart { get; set; }
        /// <summary>
        /// Gets or sets the FailedPasswordAnswerAttemptCount column value.
        /// </summary>
        int FailedPasswordAnswerAttemptCount { get; set; }
        /// <summary>
        /// Gets or sets the FailedPasswordAnswerAttemptWindowStart column value.
        /// </summary>
        System.DateTime FailedPasswordAnswerAttemptWindowStart { get; set; }
        /// <summary>
        /// Gets or sets the Comment column value.
        /// </summary>
        string Comment { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.AspnetApplications"/> association.
        /// </summary>
        AIM.Data.AspnetApplications AspnetApplications { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.AspnetUsers"/> association.
        /// </summary>
        AIM.Data.AspnetUsers AspnetUsers { get; set; }
    }
}
