//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// Interface representing the dbo.aspnet_Users table.
    /// </summary>
    public interface IAspnetUsers
    {
        /// <summary>
        /// Gets or sets the ApplicationId column value.
        /// </summary>
        System.Guid ApplicationId { get; set; }
        /// <summary>
        /// Gets or sets the UserId column value.
        /// </summary>
        System.Guid UserId { get; set; }
        /// <summary>
        /// Gets or sets the UserName column value.
        /// </summary>
        string UserName { get; set; }
        /// <summary>
        /// Gets or sets the LoweredUserName column value.
        /// </summary>
        string LoweredUserName { get; set; }
        /// <summary>
        /// Gets or sets the MobileAlias column value.
        /// </summary>
        string MobileAlias { get; set; }
        /// <summary>
        /// Gets or sets the IsAnonymous column value.
        /// </summary>
        bool IsAnonymous { get; set; }
        /// <summary>
        /// Gets or sets the LastActivityDate column value.
        /// </summary>
        System.DateTime LastActivityDate { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.AspnetMembership"/> association.
        /// </summary>
        AIM.Data.AspnetMembership AspnetMembership { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.AspnetProfile"/> association.
        /// </summary>
        AIM.Data.AspnetProfile AspnetProfile { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.AspnetApplications"/> association.
        /// </summary>
        AIM.Data.AspnetApplications AspnetApplications { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.AspnetPersonalizationPerUser"/> association.
        /// </summary>
        System.Data.Linq.EntitySet<AIM.Data.AspnetPersonalizationPerUser> AspnetPersonalizationPerUserList { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.AspnetUsersInRoles"/> association.
        /// </summary>
        System.Data.Linq.EntitySet<AIM.Data.AspnetUsersInRoles> AspnetUsersInRolesList { get; set; }
    }
}
