//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// Interface representing the dbo.ClientProperties table.
    /// </summary>
    public interface IClientProperties
    {
        /// <summary>
        /// Gets or sets the ClientId column value.
        /// </summary>
        System.Guid ClientId { get; set; }
        /// <summary>
        /// Gets or sets the AllClientsUsername column value.
        /// </summary>
        string AllClientsUsername { get; set; }
        /// <summary>
        /// Gets or sets the AllClientsPassword column value.
        /// </summary>
        string AllClientsPassword { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.Client"/> association.
        /// </summary>
        AIM.Data.Client Client { get; set; }
    }
}
