//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// Interface representing the dbo.Contact table.
    /// </summary>
    public interface IContact
    {
        /// <summary>
        /// Gets or sets the Id column value.
        /// </summary>
        System.Guid Id { get; set; }
        /// <summary>
        /// Gets or sets the ClientId column value.
        /// </summary>
        System.Guid ClientId { get; set; }
        /// <summary>
        /// Gets or sets the ContactElement column value.
        /// </summary>
        System.Xml.Linq.XElement ContactElement { get; set; }
        /// <summary>
        /// Gets or sets the Created column value.
        /// </summary>
        System.DateTime Created { get; set; }
        /// <summary>
        /// Gets or sets the Updated column value.
        /// </summary>
        Nullable<System.DateTime> Updated { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.Client"/> association.
        /// </summary>
        AIM.Data.Client Client { get; set; }
    }
}
