#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// The class representing the dbo.ClientProperties table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.ClientProperties")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(AIM.Data.ClientProperties.Metadata))]
    [System.Data.Services.Common.DataServiceKey("ClientId")]
    [System.Diagnostics.DebuggerDisplay("ClientId: {ClientId}")]
    public partial class ClientProperties
        : LinqEntityBase, ICloneable, AIM.Data.IClientProperties  
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="ClientProperties"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static ClientProperties()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="ClientProperties"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public ClientProperties()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void Initialize()
        {
            _client = default(System.Data.Linq.EntityRef<Client>);
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Guid _clientId;

        /// <summary>
        /// Gets or sets the ClientId column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ClientId", Storage = "_clientId", DbType = "uniqueidentifier NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Guid ClientId
        {
            get { return _clientId; }
            set
            {
                if (_clientId != value)
                {
                    if (_client.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnClientIdChanging(value);
                    SendPropertyChanging("ClientId");
                    _clientId = value;
                    SendPropertyChanged("ClientId");
                    OnClientIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _allClientsUsername;

        /// <summary>
        /// Gets or sets the AllClientsUsername column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "AllClientsUsername", Storage = "_allClientsUsername", DbType = "nvarchar(50) NOT NULL", CanBeNull = false)]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string AllClientsUsername
        {
            get { return _allClientsUsername; }
            set
            {
                if (_allClientsUsername != value)
                {
                    OnAllClientsUsernameChanging(value);
                    SendPropertyChanging("AllClientsUsername");
                    _allClientsUsername = value;
                    SendPropertyChanged("AllClientsUsername");
                    OnAllClientsUsernameChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _allClientsPassword;

        /// <summary>
        /// Gets or sets the AllClientsPassword column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "AllClientsPassword", Storage = "_allClientsPassword", DbType = "nvarchar(50) NOT NULL", CanBeNull = false)]
        [System.ComponentModel.DataAnnotations.StringLength(50)]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string AllClientsPassword
        {
            get { return _allClientsPassword; }
            set
            {
                if (_allClientsPassword != value)
                {
                    OnAllClientsPasswordChanging(value);
                    SendPropertyChanging("AllClientsPassword");
                    _allClientsPassword = value;
                    SendPropertyChanged("AllClientsPassword");
                    OnAllClientsPasswordChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntityRef<Client> _client;

        /// <summary>
        /// Gets or sets the <see cref="Client"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "Client_ClientProperties", Storage = "_client", ThisKey = "ClientId", OtherKey = "Id", IsForeignKey = true, DeleteOnNull = true)]
        [System.Runtime.Serialization.DataMember(Order = 4, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public Client Client
        {
            get { return (serializing && !_client.HasLoadedOrAssignedValue) ? null : _client.Entity; }
            set
            {
                Client previousValue = _client.Entity;
                if (previousValue != value || _client.HasLoadedOrAssignedValue == false)
                {
                    OnClientChanging(value);
                    SendPropertyChanging("Client");
                    if (previousValue != null)
                    {
                        _client.Entity = null;
                        previousValue.ClientProperties = null;
                    }
                    _client.Entity = value;
                    if (value != null)
                    {
                        value.ClientProperties = this;
                        _clientId = value.Id;
                    }
                    else
                    {
                        _clientId = default(System.Guid);
                    }
                    SendPropertyChanged("Client");
                    OnClientChanged();
                }
            }
        }
        
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="ClientId"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnClientIdChanging(System.Guid value);
        /// <summary>Called after <see cref="ClientId"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnClientIdChanged();
        /// <summary>Called when <see cref="AllClientsUsername"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnAllClientsUsernameChanging(string value);
        /// <summary>Called after <see cref="AllClientsUsername"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnAllClientsUsernameChanged();
        /// <summary>Called when <see cref="AllClientsPassword"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnAllClientsPasswordChanging(string value);
        /// <summary>Called after <see cref="AllClientsPassword"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnAllClientsPasswordChanged();
        /// <summary>Called when <see cref="Client"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnClientChanging(Client value);
        /// <summary>Called after <see cref="Client"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnClientChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="ClientProperties"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="ClientProperties"/> instance.</param>
        /// <returns>An instance of <see cref="ClientProperties"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static ClientProperties FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(ClientProperties));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as ClientProperties;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="ClientProperties"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="ClientProperties"/> instance.</param>
        /// <returns>An instance of <see cref="ClientProperties"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static ClientProperties FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(ClientProperties));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as ClientProperties;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public ClientProperties Clone()
        {
            return (ClientProperties)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
            _client = Detach(_client);
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414

