//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIM.MindBody.MindBodyAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Data ServiceSoap", Namespace="http://clients.mindbodyonline.com/api/0_5", ConfigurationName="MindBodyAPI.DataServiceSoap")]
    public interface DataServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/SelectDataXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        AIM.MindBody.MindBodyAPI.SelectDataXmlResult SelectDataXml(AIM.MindBody.MindBodyAPI.SelectDataXmlRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/SelectDataCSV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        AIM.MindBody.MindBodyAPI.SelectDataCSVResult SelectDataCSV(AIM.MindBody.MindBodyAPI.SelectDataCSVRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/SelectAggregateDataXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        AIM.MindBody.MindBodyAPI.SelectAggregateDataXmlResult SelectAggregateDataXml(AIM.MindBody.MindBodyAPI.SelectAggregateDataXmlRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clients.mindbodyonline.com/api/0_5/SelectAggregateDataCSV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MBRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        AIM.MindBody.MindBodyAPI.SelectAggregateDataCSVResult SelectAggregateDataCSV(AIM.MindBody.MindBodyAPI.SelectAggregateDataCSVRequest Request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectDataXmlRequest : MBRequest {
        
        private string selectSqlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SelectSql {
            get {
                return this.selectSqlField;
            }
            set {
                this.selectSqlField = value;
                this.RaisePropertyChanged("SelectSql");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectAggregateDataCSVRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectAggregateDataXmlRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectDataCSVRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectDataXmlRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class MBRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SourceCredentials sourceCredentialsField;
        
        private UserCredentials userCredentialsField;
        
        private System.Nullable<XMLDetailLevel> xMLDetailField;
        
        private System.Nullable<int> pageSizeField;
        
        private System.Nullable<int> currentPageIndexField;
        
        private string[] fieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SourceCredentials SourceCredentials {
            get {
                return this.sourceCredentialsField;
            }
            set {
                this.sourceCredentialsField = value;
                this.RaisePropertyChanged("SourceCredentials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public UserCredentials UserCredentials {
            get {
                return this.userCredentialsField;
            }
            set {
                this.userCredentialsField = value;
                this.RaisePropertyChanged("UserCredentials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<XMLDetailLevel> XMLDetail {
            get {
                return this.xMLDetailField;
            }
            set {
                this.xMLDetailField = value;
                this.RaisePropertyChanged("XMLDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("PageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> CurrentPageIndex {
            get {
                return this.currentPageIndexField;
            }
            set {
                this.currentPageIndexField = value;
                this.RaisePropertyChanged("CurrentPageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SourceCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sourceNameField;
        
        private string passwordField;
        
        private int[] siteIDsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SourceName {
            get {
                return this.sourceNameField;
            }
            set {
                this.sourceNameField = value;
                this.RaisePropertyChanged("SourceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public int[] SiteIDs {
            get {
                return this.siteIDsField;
            }
            set {
                this.siteIDsField = value;
                this.RaisePropertyChanged("SiteIDs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/API/0_4")]
    public partial class Row : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectAggregateDataCSVResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectAggregateDataXmlResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectDataCSVResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectDataXmlResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class MBResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusCode statusField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private XMLDetailLevel xMLDetailField;
        
        private int resultCountField;
        
        private int currentPageIndexField;
        
        private int totalPageCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusCode Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public XMLDetailLevel XMLDetail {
            get {
                return this.xMLDetailField;
            }
            set {
                this.xMLDetailField = value;
                this.RaisePropertyChanged("XMLDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ResultCount {
            get {
                return this.resultCountField;
            }
            set {
                this.resultCountField = value;
                this.RaisePropertyChanged("ResultCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CurrentPageIndex {
            get {
                return this.currentPageIndexField;
            }
            set {
                this.currentPageIndexField = value;
                this.RaisePropertyChanged("CurrentPageIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int TotalPageCount {
            get {
                return this.totalPageCountField;
            }
            set {
                this.totalPageCountField = value;
                this.RaisePropertyChanged("TotalPageCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public enum StatusCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        InvalidCredentials,
        
        /// <remarks/>
        InvalidParameters,
        
        /// <remarks/>
        InternalException,
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        FailedAction,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public enum XMLDetailLevel {
        
        /// <remarks/>
        Bare,
        
        /// <remarks/>
        Basic,
        
        /// <remarks/>
        Full,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectAggregateDataCSVResult : MBResult {
        
        private string cSVField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CSV {
            get {
                return this.cSVField;
            }
            set {
                this.cSVField = value;
                this.RaisePropertyChanged("CSV");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectAggregateDataXmlResult : MBResult {
        
        private Row[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Row[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectDataCSVResult : MBResult {
        
        private string cSVField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CSV {
            get {
                return this.cSVField;
            }
            set {
                this.cSVField = value;
                this.RaisePropertyChanged("CSV");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectDataXmlResult : MBResult {
        
        private Row[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Row[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class UserCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private int[] siteIDsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public int[] SiteIDs {
            get {
                return this.siteIDsField;
            }
            set {
                this.siteIDsField = value;
                this.RaisePropertyChanged("SiteIDs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectAggregateDataCSVRequest : MBRequest {
        
        private string selectSqlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SelectSql {
            get {
                return this.selectSqlField;
            }
            set {
                this.selectSqlField = value;
                this.RaisePropertyChanged("SelectSql");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectAggregateDataXmlRequest : MBRequest {
        
        private string selectSqlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SelectSql {
            get {
                return this.selectSqlField;
            }
            set {
                this.selectSqlField = value;
                this.RaisePropertyChanged("SelectSql");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://clients.mindbodyonline.com/api/0_5")]
    public partial class SelectDataCSVRequest : MBRequest {
        
        private string selectSqlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SelectSql {
            get {
                return this.selectSqlField;
            }
            set {
                this.selectSqlField = value;
                this.RaisePropertyChanged("SelectSql");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceSoapChannel : AIM.MindBody.MindBodyAPI.DataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceSoapClient : System.ServiceModel.ClientBase<AIM.MindBody.MindBodyAPI.DataServiceSoap>, AIM.MindBody.MindBodyAPI.DataServiceSoap {
        
        public DataServiceSoapClient() {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIM.MindBody.MindBodyAPI.SelectDataXmlResult SelectDataXml(AIM.MindBody.MindBodyAPI.SelectDataXmlRequest Request) {
            return base.Channel.SelectDataXml(Request);
        }
        
        public AIM.MindBody.MindBodyAPI.SelectDataCSVResult SelectDataCSV(AIM.MindBody.MindBodyAPI.SelectDataCSVRequest Request) {
            return base.Channel.SelectDataCSV(Request);
        }
        
        public AIM.MindBody.MindBodyAPI.SelectAggregateDataXmlResult SelectAggregateDataXml(AIM.MindBody.MindBodyAPI.SelectAggregateDataXmlRequest Request) {
            return base.Channel.SelectAggregateDataXml(Request);
        }
        
        public AIM.MindBody.MindBodyAPI.SelectAggregateDataCSVResult SelectAggregateDataCSV(AIM.MindBody.MindBodyAPI.SelectAggregateDataCSVRequest Request) {
            return base.Channel.SelectAggregateDataCSV(Request);
        }
    }
}
