//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// Interface representing the dbo.aspnet_PersonalizationPerUser table.
    /// </summary>
    public interface IAspnetPersonalizationPerUser
    {
        /// <summary>
        /// Gets or sets the Id column value.
        /// </summary>
        System.Guid Id { get; set; }
        /// <summary>
        /// Gets or sets the PathId column value.
        /// </summary>
        Nullable<System.Guid> PathId { get; set; }
        /// <summary>
        /// Gets or sets the UserId column value.
        /// </summary>
        Nullable<System.Guid> UserId { get; set; }
        /// <summary>
        /// Gets or sets the PageSettings column value.
        /// </summary>
        System.Data.Linq.Binary PageSettings { get; set; }
        /// <summary>
        /// Gets or sets the LastUpdatedDate column value.
        /// </summary>
        System.DateTime LastUpdatedDate { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.AspnetPaths"/> association.
        /// </summary>
        AIM.Data.AspnetPaths AspnetPaths { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.AspnetUsers"/> association.
        /// </summary>
        AIM.Data.AspnetUsers AspnetUsers { get; set; }
    }
}
