//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// Interface representing the dbo.ClientFileImport table.
    /// </summary>
    public interface IClientFileImport
    {
        /// <summary>
        /// Gets or sets the Id column value.
        /// </summary>
        System.Guid Id { get; set; }
        /// <summary>
        /// Gets or sets the ClientId column value.
        /// </summary>
        System.Guid ClientId { get; set; }
        /// <summary>
        /// Gets or sets the UploadFilePath column value.
        /// </summary>
        string UploadFilePath { get; set; }
        /// <summary>
        /// Gets or sets the ImportedFilePath column value.
        /// </summary>
        string ImportedFilePath { get; set; }
        /// <summary>
        /// Gets or sets the RecordsImported column value.
        /// </summary>
        int RecordsImported { get; set; }
        /// <summary>
        /// Gets or sets the RecordsFailed column value.
        /// </summary>
        int RecordsFailed { get; set; }
        /// <summary>
        /// Gets or sets the LastUpdated column value.
        /// </summary>
        System.DateTime LastUpdated { get; set; }
        /// <summary>
        /// Gets or sets the Processed column value.
        /// </summary>
        Nullable<System.DateTime> Processed { get; set; }
        /// <summary>
        /// Gets or sets the <see cref="T:AIM.Data.Client"/> association.
        /// </summary>
        AIM.Data.Client Client { get; set; }
    }
}
