#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// The class representing the dbo.aspnet_WebEvent_Events table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.aspnet_WebEvent_Events")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(AIM.Data.AspnetWebEventEvents.Metadata))]
    [System.Data.Services.Common.DataServiceKey("EventId")]
    [System.Diagnostics.DebuggerDisplay("EventId: {EventId}")]
    public partial class AspnetWebEventEvents
        : LinqEntityBase, ICloneable, AIM.Data.IAspnetWebEventEvents  
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="AspnetWebEventEvents"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static AspnetWebEventEvents()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="AspnetWebEventEvents"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public AspnetWebEventEvents()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void Initialize()
        {
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _eventId;

        /// <summary>
        /// Gets or sets the EventId column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "EventId", Storage = "_eventId", DbType = "char(32) NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.ComponentModel.DataAnnotations.StringLength(32)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string EventId
        {
            get { return _eventId; }
            set
            {
                if (_eventId != value)
                {
                    OnEventIdChanging(value);
                    SendPropertyChanging("EventId");
                    _eventId = value;
                    SendPropertyChanged("EventId");
                    OnEventIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.DateTime _eventTimeUtc;

        /// <summary>
        /// Gets or sets the EventTimeUtc column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "EventTimeUtc", Storage = "_eventTimeUtc", DbType = "datetime NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.DateTime EventTimeUtc
        {
            get { return _eventTimeUtc; }
            set
            {
                if (_eventTimeUtc != value)
                {
                    OnEventTimeUtcChanging(value);
                    SendPropertyChanging("EventTimeUtc");
                    _eventTimeUtc = value;
                    SendPropertyChanged("EventTimeUtc");
                    OnEventTimeUtcChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.DateTime _eventTime;

        /// <summary>
        /// Gets or sets the EventTime column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "EventTime", Storage = "_eventTime", DbType = "datetime NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.DateTime EventTime
        {
            get { return _eventTime; }
            set
            {
                if (_eventTime != value)
                {
                    OnEventTimeChanging(value);
                    SendPropertyChanging("EventTime");
                    _eventTime = value;
                    SendPropertyChanged("EventTime");
                    OnEventTimeChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _eventType;

        /// <summary>
        /// Gets or sets the EventType column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "EventType", Storage = "_eventType", DbType = "nvarchar(256) NOT NULL", CanBeNull = false)]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string EventType
        {
            get { return _eventType; }
            set
            {
                if (_eventType != value)
                {
                    OnEventTypeChanging(value);
                    SendPropertyChanging("EventType");
                    _eventType = value;
                    SendPropertyChanged("EventType");
                    OnEventTypeChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private decimal _eventSequence;

        /// <summary>
        /// Gets or sets the EventSequence column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "EventSequence", Storage = "_eventSequence", DbType = "decimal(19,0) NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public decimal EventSequence
        {
            get { return _eventSequence; }
            set
            {
                if (_eventSequence != value)
                {
                    OnEventSequenceChanging(value);
                    SendPropertyChanging("EventSequence");
                    _eventSequence = value;
                    SendPropertyChanged("EventSequence");
                    OnEventSequenceChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private decimal _eventOccurrence;

        /// <summary>
        /// Gets or sets the EventOccurrence column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "EventOccurrence", Storage = "_eventOccurrence", DbType = "decimal(19,0) NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public decimal EventOccurrence
        {
            get { return _eventOccurrence; }
            set
            {
                if (_eventOccurrence != value)
                {
                    OnEventOccurrenceChanging(value);
                    SendPropertyChanging("EventOccurrence");
                    _eventOccurrence = value;
                    SendPropertyChanged("EventOccurrence");
                    OnEventOccurrenceChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private int _eventCode;

        /// <summary>
        /// Gets or sets the EventCode column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "EventCode", Storage = "_eventCode", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 7)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public int EventCode
        {
            get { return _eventCode; }
            set
            {
                if (_eventCode != value)
                {
                    OnEventCodeChanging(value);
                    SendPropertyChanging("EventCode");
                    _eventCode = value;
                    SendPropertyChanged("EventCode");
                    OnEventCodeChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private int _eventDetailCode;

        /// <summary>
        /// Gets or sets the EventDetailCode column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "EventDetailCode", Storage = "_eventDetailCode", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 8)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public int EventDetailCode
        {
            get { return _eventDetailCode; }
            set
            {
                if (_eventDetailCode != value)
                {
                    OnEventDetailCodeChanging(value);
                    SendPropertyChanging("EventDetailCode");
                    _eventDetailCode = value;
                    SendPropertyChanged("EventDetailCode");
                    OnEventDetailCodeChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _message;

        /// <summary>
        /// Gets or sets the Message column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "Message", Storage = "_message", DbType = "nvarchar(1024)")]
        [System.ComponentModel.DataAnnotations.StringLength(1024)]
        [System.Runtime.Serialization.DataMember(Order = 9)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string Message
        {
            get { return _message; }
            set
            {
                if (_message != value)
                {
                    OnMessageChanging(value);
                    SendPropertyChanging("Message");
                    _message = value;
                    SendPropertyChanged("Message");
                    OnMessageChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _applicationPath;

        /// <summary>
        /// Gets or sets the ApplicationPath column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ApplicationPath", Storage = "_applicationPath", DbType = "nvarchar(256)")]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [System.Runtime.Serialization.DataMember(Order = 10)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string ApplicationPath
        {
            get { return _applicationPath; }
            set
            {
                if (_applicationPath != value)
                {
                    OnApplicationPathChanging(value);
                    SendPropertyChanging("ApplicationPath");
                    _applicationPath = value;
                    SendPropertyChanged("ApplicationPath");
                    OnApplicationPathChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _applicationVirtualPath;

        /// <summary>
        /// Gets or sets the ApplicationVirtualPath column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ApplicationVirtualPath", Storage = "_applicationVirtualPath", DbType = "nvarchar(256)")]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [System.Runtime.Serialization.DataMember(Order = 11)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string ApplicationVirtualPath
        {
            get { return _applicationVirtualPath; }
            set
            {
                if (_applicationVirtualPath != value)
                {
                    OnApplicationVirtualPathChanging(value);
                    SendPropertyChanging("ApplicationVirtualPath");
                    _applicationVirtualPath = value;
                    SendPropertyChanged("ApplicationVirtualPath");
                    OnApplicationVirtualPathChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _machineName;

        /// <summary>
        /// Gets or sets the MachineName column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "MachineName", Storage = "_machineName", DbType = "nvarchar(256) NOT NULL", CanBeNull = false)]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [System.Runtime.Serialization.DataMember(Order = 12)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string MachineName
        {
            get { return _machineName; }
            set
            {
                if (_machineName != value)
                {
                    OnMachineNameChanging(value);
                    SendPropertyChanging("MachineName");
                    _machineName = value;
                    SendPropertyChanged("MachineName");
                    OnMachineNameChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _requestUrl;

        /// <summary>
        /// Gets or sets the RequestUrl column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "RequestUrl", Storage = "_requestUrl", DbType = "nvarchar(1024)")]
        [System.ComponentModel.DataAnnotations.StringLength(1024)]
        [System.Runtime.Serialization.DataMember(Order = 13)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string RequestUrl
        {
            get { return _requestUrl; }
            set
            {
                if (_requestUrl != value)
                {
                    OnRequestUrlChanging(value);
                    SendPropertyChanging("RequestUrl");
                    _requestUrl = value;
                    SendPropertyChanged("RequestUrl");
                    OnRequestUrlChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _exceptionType;

        /// <summary>
        /// Gets or sets the ExceptionType column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ExceptionType", Storage = "_exceptionType", DbType = "nvarchar(256)")]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [System.Runtime.Serialization.DataMember(Order = 14)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string ExceptionType
        {
            get { return _exceptionType; }
            set
            {
                if (_exceptionType != value)
                {
                    OnExceptionTypeChanging(value);
                    SendPropertyChanging("ExceptionType");
                    _exceptionType = value;
                    SendPropertyChanged("ExceptionType");
                    OnExceptionTypeChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _details;

        /// <summary>
        /// Gets or sets the Details column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "Details", Storage = "_details", DbType = "ntext", UpdateCheck = System.Data.Linq.Mapping.UpdateCheck.Never)]
        [System.Runtime.Serialization.DataMember(Order = 15)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string Details
        {
            get { return _details; }
            set
            {
                if (_details != value)
                {
                    OnDetailsChanging(value);
                    SendPropertyChanging("Details");
                    _details = value;
                    SendPropertyChanged("Details");
                    OnDetailsChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="EventId"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventIdChanging(string value);
        /// <summary>Called after <see cref="EventId"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventIdChanged();
        /// <summary>Called when <see cref="EventTimeUtc"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventTimeUtcChanging(System.DateTime value);
        /// <summary>Called after <see cref="EventTimeUtc"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventTimeUtcChanged();
        /// <summary>Called when <see cref="EventTime"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventTimeChanging(System.DateTime value);
        /// <summary>Called after <see cref="EventTime"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventTimeChanged();
        /// <summary>Called when <see cref="EventType"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventTypeChanging(string value);
        /// <summary>Called after <see cref="EventType"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventTypeChanged();
        /// <summary>Called when <see cref="EventSequence"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventSequenceChanging(decimal value);
        /// <summary>Called after <see cref="EventSequence"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventSequenceChanged();
        /// <summary>Called when <see cref="EventOccurrence"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventOccurrenceChanging(decimal value);
        /// <summary>Called after <see cref="EventOccurrence"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventOccurrenceChanged();
        /// <summary>Called when <see cref="EventCode"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventCodeChanging(int value);
        /// <summary>Called after <see cref="EventCode"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventCodeChanged();
        /// <summary>Called when <see cref="EventDetailCode"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventDetailCodeChanging(int value);
        /// <summary>Called after <see cref="EventDetailCode"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnEventDetailCodeChanged();
        /// <summary>Called when <see cref="Message"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnMessageChanging(string value);
        /// <summary>Called after <see cref="Message"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnMessageChanged();
        /// <summary>Called when <see cref="ApplicationPath"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnApplicationPathChanging(string value);
        /// <summary>Called after <see cref="ApplicationPath"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnApplicationPathChanged();
        /// <summary>Called when <see cref="ApplicationVirtualPath"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnApplicationVirtualPathChanging(string value);
        /// <summary>Called after <see cref="ApplicationVirtualPath"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnApplicationVirtualPathChanged();
        /// <summary>Called when <see cref="MachineName"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnMachineNameChanging(string value);
        /// <summary>Called after <see cref="MachineName"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnMachineNameChanged();
        /// <summary>Called when <see cref="RequestUrl"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRequestUrlChanging(string value);
        /// <summary>Called after <see cref="RequestUrl"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRequestUrlChanged();
        /// <summary>Called when <see cref="ExceptionType"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnExceptionTypeChanging(string value);
        /// <summary>Called after <see cref="ExceptionType"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnExceptionTypeChanged();
        /// <summary>Called when <see cref="Details"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnDetailsChanging(string value);
        /// <summary>Called after <see cref="Details"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnDetailsChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="AspnetWebEventEvents"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="AspnetWebEventEvents"/> instance.</param>
        /// <returns>An instance of <see cref="AspnetWebEventEvents"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static AspnetWebEventEvents FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(AspnetWebEventEvents));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as AspnetWebEventEvents;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="AspnetWebEventEvents"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="AspnetWebEventEvents"/> instance.</param>
        /// <returns>An instance of <see cref="AspnetWebEventEvents"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static AspnetWebEventEvents FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(AspnetWebEventEvents));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as AspnetWebEventEvents;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public AspnetWebEventEvents Clone()
        {
            return (AspnetWebEventEvents)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414

