#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// The class representing the dbo.aspnet_Applications table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.aspnet_Applications")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(AIM.Data.AspnetApplications.Metadata))]
    [System.Data.Services.Common.DataServiceKey("ApplicationId")]
    [System.Diagnostics.DebuggerDisplay("ApplicationId: {ApplicationId}")]
    public partial class AspnetApplications
        : LinqEntityBase, ICloneable, AIM.Data.IAspnetApplications  
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="AspnetApplications"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static AspnetApplications()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="AspnetApplications"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public AspnetApplications()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void Initialize()
        {
            _aspnetMembershipList = new System.Data.Linq.EntitySet<AspnetMembership>(OnAspnetMembershipListAdd, OnAspnetMembershipListRemove);
            _aspnetPathsList = new System.Data.Linq.EntitySet<AspnetPaths>(OnAspnetPathsListAdd, OnAspnetPathsListRemove);
            _aspnetRolesList = new System.Data.Linq.EntitySet<AspnetRoles>(OnAspnetRolesListAdd, OnAspnetRolesListRemove);
            _aspnetUsersList = new System.Data.Linq.EntitySet<AspnetUsers>(OnAspnetUsersListAdd, OnAspnetUsersListRemove);
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _applicationName;

        /// <summary>
        /// Gets or sets the ApplicationName column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ApplicationName", Storage = "_applicationName", DbType = "nvarchar(256) NOT NULL", CanBeNull = false)]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string ApplicationName
        {
            get { return _applicationName; }
            set
            {
                if (_applicationName != value)
                {
                    OnApplicationNameChanging(value);
                    SendPropertyChanging("ApplicationName");
                    _applicationName = value;
                    SendPropertyChanged("ApplicationName");
                    OnApplicationNameChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _loweredApplicationName;

        /// <summary>
        /// Gets or sets the LoweredApplicationName column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "LoweredApplicationName", Storage = "_loweredApplicationName", DbType = "nvarchar(256) NOT NULL", CanBeNull = false)]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string LoweredApplicationName
        {
            get { return _loweredApplicationName; }
            set
            {
                if (_loweredApplicationName != value)
                {
                    OnLoweredApplicationNameChanging(value);
                    SendPropertyChanging("LoweredApplicationName");
                    _loweredApplicationName = value;
                    SendPropertyChanged("LoweredApplicationName");
                    OnLoweredApplicationNameChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Guid _applicationId;

        /// <summary>
        /// Gets or sets the ApplicationId column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ApplicationId", Storage = "_applicationId", DbType = "uniqueidentifier NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Guid ApplicationId
        {
            get { return _applicationId; }
            set
            {
                if (_applicationId != value)
                {
                    OnApplicationIdChanging(value);
                    SendPropertyChanging("ApplicationId");
                    _applicationId = value;
                    SendPropertyChanged("ApplicationId");
                    OnApplicationIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _description;

        /// <summary>
        /// Gets or sets the Description column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "Description", Storage = "_description", DbType = "nvarchar(256)")]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    OnDescriptionChanging(value);
                    SendPropertyChanging("Description");
                    _description = value;
                    SendPropertyChanged("Description");
                    OnDescriptionChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntitySet<AspnetMembership> _aspnetMembershipList;

        /// <summary>
        /// Gets or sets the <see cref="AspnetMembership"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "AspnetApplications_AspnetMembership", Storage = "_aspnetMembershipList", ThisKey = "ApplicationId", OtherKey = "ApplicationId")]
        [System.Runtime.Serialization.DataMember(Order=5, EmitDefaultValue=false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Data.Linq.EntitySet<AspnetMembership> AspnetMembershipList
        {
            get { return (serializing && !_aspnetMembershipList.HasLoadedOrAssignedValues) ? null : _aspnetMembershipList; }
            set { _aspnetMembershipList.Assign(value); }
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnAspnetMembershipListAdd(AspnetMembership entity)
        {
            SendPropertyChanging(null);
            entity.AspnetApplications = this;
            SendPropertyChanged(null);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnAspnetMembershipListRemove(AspnetMembership entity)
        {
            SendPropertyChanging(null);
            entity.AspnetApplications = null;
            SendPropertyChanged(null);
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntitySet<AspnetPaths> _aspnetPathsList;

        /// <summary>
        /// Gets or sets the <see cref="AspnetPaths"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "AspnetApplications_AspnetPaths", Storage = "_aspnetPathsList", ThisKey = "ApplicationId", OtherKey = "ApplicationId")]
        [System.Runtime.Serialization.DataMember(Order=6, EmitDefaultValue=false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Data.Linq.EntitySet<AspnetPaths> AspnetPathsList
        {
            get { return (serializing && !_aspnetPathsList.HasLoadedOrAssignedValues) ? null : _aspnetPathsList; }
            set { _aspnetPathsList.Assign(value); }
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnAspnetPathsListAdd(AspnetPaths entity)
        {
            SendPropertyChanging(null);
            entity.AspnetApplications = this;
            SendPropertyChanged(null);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnAspnetPathsListRemove(AspnetPaths entity)
        {
            SendPropertyChanging(null);
            entity.AspnetApplications = null;
            SendPropertyChanged(null);
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntitySet<AspnetRoles> _aspnetRolesList;

        /// <summary>
        /// Gets or sets the <see cref="AspnetRoles"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "AspnetApplications_AspnetRoles", Storage = "_aspnetRolesList", ThisKey = "ApplicationId", OtherKey = "ApplicationId")]
        [System.Runtime.Serialization.DataMember(Order=7, EmitDefaultValue=false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Data.Linq.EntitySet<AspnetRoles> AspnetRolesList
        {
            get { return (serializing && !_aspnetRolesList.HasLoadedOrAssignedValues) ? null : _aspnetRolesList; }
            set { _aspnetRolesList.Assign(value); }
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnAspnetRolesListAdd(AspnetRoles entity)
        {
            SendPropertyChanging(null);
            entity.AspnetApplications = this;
            SendPropertyChanged(null);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnAspnetRolesListRemove(AspnetRoles entity)
        {
            SendPropertyChanging(null);
            entity.AspnetApplications = null;
            SendPropertyChanged(null);
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntitySet<AspnetUsers> _aspnetUsersList;

        /// <summary>
        /// Gets or sets the <see cref="AspnetUsers"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "AspnetApplications_AspnetUsers", Storage = "_aspnetUsersList", ThisKey = "ApplicationId", OtherKey = "ApplicationId")]
        [System.Runtime.Serialization.DataMember(Order=8, EmitDefaultValue=false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Data.Linq.EntitySet<AspnetUsers> AspnetUsersList
        {
            get { return (serializing && !_aspnetUsersList.HasLoadedOrAssignedValues) ? null : _aspnetUsersList; }
            set { _aspnetUsersList.Assign(value); }
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnAspnetUsersListAdd(AspnetUsers entity)
        {
            SendPropertyChanging(null);
            entity.AspnetApplications = this;
            SendPropertyChanged(null);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnAspnetUsersListRemove(AspnetUsers entity)
        {
            SendPropertyChanging(null);
            entity.AspnetApplications = null;
            SendPropertyChanged(null);
        }
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="ApplicationName"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnApplicationNameChanging(string value);
        /// <summary>Called after <see cref="ApplicationName"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnApplicationNameChanged();
        /// <summary>Called when <see cref="LoweredApplicationName"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLoweredApplicationNameChanging(string value);
        /// <summary>Called after <see cref="LoweredApplicationName"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLoweredApplicationNameChanged();
        /// <summary>Called when <see cref="ApplicationId"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnApplicationIdChanging(System.Guid value);
        /// <summary>Called after <see cref="ApplicationId"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnApplicationIdChanged();
        /// <summary>Called when <see cref="Description"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnDescriptionChanging(string value);
        /// <summary>Called after <see cref="Description"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnDescriptionChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="AspnetApplications"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="AspnetApplications"/> instance.</param>
        /// <returns>An instance of <see cref="AspnetApplications"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static AspnetApplications FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(AspnetApplications));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as AspnetApplications;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="AspnetApplications"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="AspnetApplications"/> instance.</param>
        /// <returns>An instance of <see cref="AspnetApplications"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static AspnetApplications FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(AspnetApplications));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as AspnetApplications;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public AspnetApplications Clone()
        {
            return (AspnetApplications)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
            _aspnetMembershipList = Detach(_aspnetMembershipList, OnAspnetMembershipListAdd, OnAspnetMembershipListRemove);
            _aspnetPathsList = Detach(_aspnetPathsList, OnAspnetPathsListAdd, OnAspnetPathsListRemove);
            _aspnetRolesList = Detach(_aspnetRolesList, OnAspnetRolesListAdd, OnAspnetRolesListRemove);
            _aspnetUsersList = Detach(_aspnetUsersList, OnAspnetUsersListAdd, OnAspnetUsersListRemove);
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414

