#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// The class representing the dbo.aspnet_UsersInRoles table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.aspnet_UsersInRoles")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(AIM.Data.AspnetUsersInRoles.Metadata))]
    [System.Data.Services.Common.DataServiceKey("UserId", "RoleId")]
    [System.Diagnostics.DebuggerDisplay("UserId: {UserId}, RoleId: {RoleId}")]
    public partial class AspnetUsersInRoles
        : LinqEntityBase, ICloneable, AIM.Data.IAspnetUsersInRoles  
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="AspnetUsersInRoles"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static AspnetUsersInRoles()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="AspnetUsersInRoles"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public AspnetUsersInRoles()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void Initialize()
        {
            _aspnetRoles = default(System.Data.Linq.EntityRef<AspnetRoles>);
            _aspnetUsers = default(System.Data.Linq.EntityRef<AspnetUsers>);
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Guid _userId;

        /// <summary>
        /// Gets or sets the UserId column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "UserId", Storage = "_userId", DbType = "uniqueidentifier NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Guid UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (_aspnetUsers.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnUserIdChanging(value);
                    SendPropertyChanging("UserId");
                    _userId = value;
                    SendPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Guid _roleId;

        /// <summary>
        /// Gets or sets the RoleId column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "RoleId", Storage = "_roleId", DbType = "uniqueidentifier NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Guid RoleId
        {
            get { return _roleId; }
            set
            {
                if (_roleId != value)
                {
                    if (_aspnetRoles.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnRoleIdChanging(value);
                    SendPropertyChanging("RoleId");
                    _roleId = value;
                    SendPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntityRef<AspnetRoles> _aspnetRoles;

        /// <summary>
        /// Gets or sets the <see cref="AspnetRoles"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "AspnetRoles_AspnetUsersInRoles", Storage = "_aspnetRoles", ThisKey = "RoleId", OtherKey = "RoleId", IsForeignKey = true, DeleteOnNull = true)]
        [System.Runtime.Serialization.DataMember(Order = 3, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public AspnetRoles AspnetRoles
        {
            get { return (serializing && !_aspnetRoles.HasLoadedOrAssignedValue) ? null : _aspnetRoles.Entity; }
            set
            {
                AspnetRoles previousValue = _aspnetRoles.Entity;
                if (previousValue != value || _aspnetRoles.HasLoadedOrAssignedValue == false)
                {
                    OnAspnetRolesChanging(value);
                    SendPropertyChanging("AspnetRoles");
                    if (previousValue != null)
                    {
                        _aspnetRoles.Entity = null;
                        previousValue.AspnetUsersInRolesList.Remove(this);
                    }
                    _aspnetRoles.Entity = value;
                    if (value != null)
                    {
                        value.AspnetUsersInRolesList.Add(this);
                        _roleId = value.RoleId;
                    }
                    else
                    {
                        _roleId = default(System.Guid);
                    }
                    SendPropertyChanged("AspnetRoles");
                    OnAspnetRolesChanged();
                }
            }
        }
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntityRef<AspnetUsers> _aspnetUsers;

        /// <summary>
        /// Gets or sets the <see cref="AspnetUsers"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "AspnetUsers_AspnetUsersInRoles", Storage = "_aspnetUsers", ThisKey = "UserId", OtherKey = "UserId", IsForeignKey = true, DeleteOnNull = true)]
        [System.Runtime.Serialization.DataMember(Order = 4, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public AspnetUsers AspnetUsers
        {
            get { return (serializing && !_aspnetUsers.HasLoadedOrAssignedValue) ? null : _aspnetUsers.Entity; }
            set
            {
                AspnetUsers previousValue = _aspnetUsers.Entity;
                if (previousValue != value || _aspnetUsers.HasLoadedOrAssignedValue == false)
                {
                    OnAspnetUsersChanging(value);
                    SendPropertyChanging("AspnetUsers");
                    if (previousValue != null)
                    {
                        _aspnetUsers.Entity = null;
                        previousValue.AspnetUsersInRolesList.Remove(this);
                    }
                    _aspnetUsers.Entity = value;
                    if (value != null)
                    {
                        value.AspnetUsersInRolesList.Add(this);
                        _userId = value.UserId;
                    }
                    else
                    {
                        _userId = default(System.Guid);
                    }
                    SendPropertyChanged("AspnetUsers");
                    OnAspnetUsersChanged();
                }
            }
        }
        
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="UserId"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnUserIdChanging(System.Guid value);
        /// <summary>Called after <see cref="UserId"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnUserIdChanged();
        /// <summary>Called when <see cref="RoleId"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoleIdChanging(System.Guid value);
        /// <summary>Called after <see cref="RoleId"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoleIdChanged();
        /// <summary>Called when <see cref="AspnetRoles"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnAspnetRolesChanging(AspnetRoles value);
        /// <summary>Called after <see cref="AspnetRoles"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnAspnetRolesChanged();
        /// <summary>Called when <see cref="AspnetUsers"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnAspnetUsersChanging(AspnetUsers value);
        /// <summary>Called after <see cref="AspnetUsers"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnAspnetUsersChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="AspnetUsersInRoles"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="AspnetUsersInRoles"/> instance.</param>
        /// <returns>An instance of <see cref="AspnetUsersInRoles"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static AspnetUsersInRoles FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(AspnetUsersInRoles));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as AspnetUsersInRoles;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="AspnetUsersInRoles"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="AspnetUsersInRoles"/> instance.</param>
        /// <returns>An instance of <see cref="AspnetUsersInRoles"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static AspnetUsersInRoles FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(AspnetUsersInRoles));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as AspnetUsersInRoles;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public AspnetUsersInRoles Clone()
        {
            return (AspnetUsersInRoles)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
            _aspnetRoles = Detach(_aspnetRoles);
            _aspnetUsers = Detach(_aspnetUsers);
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414

