#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace AIM.Data
{
    /// <summary>
    /// The class representing the dbo.aspnet_Roles table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.aspnet_Roles")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(AIM.Data.AspnetRoles.Metadata))]
    [System.Data.Services.Common.DataServiceKey("RoleId")]
    [System.Diagnostics.DebuggerDisplay("RoleId: {RoleId}")]
    public partial class AspnetRoles
        : LinqEntityBase, ICloneable, AIM.Data.IAspnetRoles  
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="AspnetRoles"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static AspnetRoles()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="AspnetRoles"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public AspnetRoles()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void Initialize()
        {
            _aspnetApplications = default(System.Data.Linq.EntityRef<AspnetApplications>);
            _aspnetUsersInRolesList = new System.Data.Linq.EntitySet<AspnetUsersInRoles>(OnAspnetUsersInRolesListAdd, OnAspnetUsersInRolesListRemove);
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Guid _applicationId;

        /// <summary>
        /// Gets or sets the ApplicationId column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ApplicationId", Storage = "_applicationId", DbType = "uniqueidentifier NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Guid ApplicationId
        {
            get { return _applicationId; }
            set
            {
                if (_applicationId != value)
                {
                    if (_aspnetApplications.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnApplicationIdChanging(value);
                    SendPropertyChanging("ApplicationId");
                    _applicationId = value;
                    SendPropertyChanged("ApplicationId");
                    OnApplicationIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Guid _roleId;

        /// <summary>
        /// Gets or sets the RoleId column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "RoleId", Storage = "_roleId", DbType = "uniqueidentifier NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Guid RoleId
        {
            get { return _roleId; }
            set
            {
                if (_roleId != value)
                {
                    OnRoleIdChanging(value);
                    SendPropertyChanging("RoleId");
                    _roleId = value;
                    SendPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _roleName;

        /// <summary>
        /// Gets or sets the RoleName column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "RoleName", Storage = "_roleName", DbType = "nvarchar(256) NOT NULL", CanBeNull = false)]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string RoleName
        {
            get { return _roleName; }
            set
            {
                if (_roleName != value)
                {
                    OnRoleNameChanging(value);
                    SendPropertyChanging("RoleName");
                    _roleName = value;
                    SendPropertyChanged("RoleName");
                    OnRoleNameChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _loweredRoleName;

        /// <summary>
        /// Gets or sets the LoweredRoleName column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "LoweredRoleName", Storage = "_loweredRoleName", DbType = "nvarchar(256) NOT NULL", CanBeNull = false)]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string LoweredRoleName
        {
            get { return _loweredRoleName; }
            set
            {
                if (_loweredRoleName != value)
                {
                    OnLoweredRoleNameChanging(value);
                    SendPropertyChanging("LoweredRoleName");
                    _loweredRoleName = value;
                    SendPropertyChanged("LoweredRoleName");
                    OnLoweredRoleNameChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private string _description;

        /// <summary>
        /// Gets or sets the Description column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "Description", Storage = "_description", DbType = "nvarchar(256)")]
        [System.ComponentModel.DataAnnotations.StringLength(256)]
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    OnDescriptionChanging(value);
                    SendPropertyChanging("Description");
                    _description = value;
                    SendPropertyChanged("Description");
                    OnDescriptionChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntityRef<AspnetApplications> _aspnetApplications;

        /// <summary>
        /// Gets or sets the <see cref="AspnetApplications"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "AspnetApplications_AspnetRoles", Storage = "_aspnetApplications", ThisKey = "ApplicationId", OtherKey = "ApplicationId", IsForeignKey = true, DeleteOnNull = true)]
        [System.Runtime.Serialization.DataMember(Order = 6, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public AspnetApplications AspnetApplications
        {
            get { return (serializing && !_aspnetApplications.HasLoadedOrAssignedValue) ? null : _aspnetApplications.Entity; }
            set
            {
                AspnetApplications previousValue = _aspnetApplications.Entity;
                if (previousValue != value || _aspnetApplications.HasLoadedOrAssignedValue == false)
                {
                    OnAspnetApplicationsChanging(value);
                    SendPropertyChanging("AspnetApplications");
                    if (previousValue != null)
                    {
                        _aspnetApplications.Entity = null;
                        previousValue.AspnetRolesList.Remove(this);
                    }
                    _aspnetApplications.Entity = value;
                    if (value != null)
                    {
                        value.AspnetRolesList.Add(this);
                        _applicationId = value.ApplicationId;
                    }
                    else
                    {
                        _applicationId = default(System.Guid);
                    }
                    SendPropertyChanged("AspnetApplications");
                    OnAspnetApplicationsChanged();
                }
            }
        }
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntitySet<AspnetUsersInRoles> _aspnetUsersInRolesList;

        /// <summary>
        /// Gets or sets the <see cref="AspnetUsersInRoles"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "AspnetRoles_AspnetUsersInRoles", Storage = "_aspnetUsersInRolesList", ThisKey = "RoleId", OtherKey = "RoleId")]
        [System.Runtime.Serialization.DataMember(Order=7, EmitDefaultValue=false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Data.Linq.EntitySet<AspnetUsersInRoles> AspnetUsersInRolesList
        {
            get { return (serializing && !_aspnetUsersInRolesList.HasLoadedOrAssignedValues) ? null : _aspnetUsersInRolesList; }
            set { _aspnetUsersInRolesList.Assign(value); }
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnAspnetUsersInRolesListAdd(AspnetUsersInRoles entity)
        {
            SendPropertyChanging(null);
            entity.AspnetRoles = this;
            SendPropertyChanged(null);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnAspnetUsersInRolesListRemove(AspnetUsersInRoles entity)
        {
            SendPropertyChanging(null);
            entity.AspnetRoles = null;
            SendPropertyChanged(null);
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private System.Data.Linq.EntitySet<AspnetUsers> _aspnetUsersList;

        /// <summary>
        /// Gets or sets the Many To Many AspnetUsersList list.
        /// </summary>
        /// <value>The AspnetUsersList list.</value>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public System.Data.Linq.EntitySet<AspnetUsers> AspnetUsersList
        {
            get
            {
                if (serializing)
                    return null;

                if (_aspnetUsersList == null)
                {
                    _aspnetUsersList = new System.Data.Linq.EntitySet<AspnetUsers>(OnAspnetUsersListAdd, OnAspnetUsersListRemove);
                    _aspnetUsersList.SetSource(AspnetUsersInRolesList.Select(c => c.AspnetUsers));
                }
                return _aspnetUsersList;
            }
            set
            {
                _aspnetUsersList.Assign(value);
            }
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnAspnetUsersListAdd(AspnetUsers entity)
        {
            SendPropertyChanging(null);
            AspnetUsersInRolesList.Add(new AspnetUsersInRoles { AspnetRoles = this, AspnetUsers = entity });
            SendPropertyChanged(null);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private void OnAspnetUsersListRemove(AspnetUsers entity)
        {
            SendPropertyChanging(null);
            var aspnetUsersInRoles = AspnetUsersInRolesList.FirstOrDefault(c => c.RoleId == RoleId
                && c.UserId == entity.UserId);
            AspnetUsersInRolesList.Remove( aspnetUsersInRoles);
            SendPropertyChanged(null);
        }

        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="ApplicationId"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnApplicationIdChanging(System.Guid value);
        /// <summary>Called after <see cref="ApplicationId"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnApplicationIdChanged();
        /// <summary>Called when <see cref="RoleId"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoleIdChanging(System.Guid value);
        /// <summary>Called after <see cref="RoleId"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoleIdChanged();
        /// <summary>Called when <see cref="RoleName"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoleNameChanging(string value);
        /// <summary>Called after <see cref="RoleName"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnRoleNameChanged();
        /// <summary>Called when <see cref="LoweredRoleName"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLoweredRoleNameChanging(string value);
        /// <summary>Called after <see cref="LoweredRoleName"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnLoweredRoleNameChanged();
        /// <summary>Called when <see cref="Description"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnDescriptionChanging(string value);
        /// <summary>Called after <see cref="Description"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnDescriptionChanged();
        /// <summary>Called when <see cref="AspnetApplications"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnAspnetApplicationsChanging(AspnetApplications value);
        /// <summary>Called after <see cref="AspnetApplications"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        partial void OnAspnetApplicationsChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="AspnetRoles"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="AspnetRoles"/> instance.</param>
        /// <returns>An instance of <see cref="AspnetRoles"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static AspnetRoles FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(AspnetRoles));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as AspnetRoles;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="AspnetRoles"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="AspnetRoles"/> instance.</param>
        /// <returns>An instance of <see cref="AspnetRoles"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public static AspnetRoles FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(AspnetRoles));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as AspnetRoles;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public AspnetRoles Clone()
        {
            return (AspnetRoles)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
            _aspnetApplications = Detach(_aspnetApplications);
            _aspnetUsersInRolesList = Detach(_aspnetUsersInRolesList, OnAspnetUsersInRolesListAdd, OnAspnetUsersInRolesListRemove);
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414

