//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("CodeSmith Tools, LLC")]
[assembly: AssemblyProduct("PLINQO")]
[assembly: AssemblyCopyright("Copyright (c) 2002-2010 CodeSmith Tools, LLC.  All rights reserved.")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyVersion("5.0.0.0")]
[assembly: AssemblyFileVersion("5.0.1.1966")]
[assembly: AssemblyInformationalVersion("5.0.1.1966")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyCompany = "CodeSmith Tools, LLC";
    
    internal const string AssemblyProduct = "PLINQO";
    
    internal const string AssemblyCopyright = "Copyright (c) 2002-2010 CodeSmith Tools, LLC.  All rights reserved.";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyVersion = "5.0.0.0";
    
    internal const string AssemblyFileVersion = "5.0.1.1966";
    
    internal const string AssemblyInformationalVersion = "5.0.1.1966";
    
    private ThisAssembly() {
    }
}
