
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

namespace AIM.Data
{
    /// <summary>
    /// The DataContext manager class for the AIM database.
    /// </summary>
    public partial class DomainContext
    {
        
        private AIM.Data.AimDataManager _manager = null;
        
        /// <summary>
        /// Gets the data manager.
        /// </summary>
        /// <value>The data manager.</value>
        public AIM.Data.AimDataManager Manager
        {
            get
            {
                if (_manager == null)
                    _manager = new AIM.Data.AimDataManager(this);
                return _manager;
            }
        }
    }
}